/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Samuel David Ortiz
 */
public class FrmPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form FrmPreguntas
     */
    private int a;
    private int b;
    private int c;
    private int d;
    private int e;
    private int f;
    private int g;
    private int h;
    private int i;
    private int j;
    private int k;
    private int l;
    private int m;
    private int n;
    private int o;
    private int p;
    private int q;
    private int r;
    private int s;
    private int t;
    private int u;
    private int v;
    private int w;
    private int x;
    private int y;

    public FrmPreguntas(int b,
            int c,
            int d,
            int e,
            int f,
            int g,
            int h,
            int i,
            int j,
            int k,
            int l,
            int m,
            int n,
            int o,
            int p,
            int q,
            int r,
            int s,
            int t,
            int u,
            int v,
            int w,
            int x,
            int y
    ) {
        this.a = a;
        this.b = b;
        this.c = c;
        this.d = d;
        this.e = e;
        this.f = f;
        this.g = g;
        this.h = h;
        this.i = i;
        this.j = j;
        this.k = k;
        this.l = l;
        this.m = m;
        this.n = n;
        this.o = o;
        this.p = p;
        this.q = q;
        this.r = r;
        this.s = s;
        this.t = t;
        this.u = u;
        this.v = v;
        this.w = w;
        this.x = x;
        this.y = y;

        initComponents();

        txtPreg.append("2. ¿Cuál es el primer número del listado?" + a + "\n");
        txtPreg.append("3. ¿Cuál es el último número del listado?" + b + "\n");
        txtPreg.append("4. ¿Cuál es el 739vo. número primo generado?" + c + "\n");
        txtPreg.append("5. ¿Cuál es el 1254vo. número primo generado?" + d + "\n");
        txtPreg.append("6. ¿Cuál es el 1551vo. número primo generado?" + e + "\n");
        txtPreg.append("7. ¿Cuál es el 1739vo. número primo generado?" + f + "\n");
        txtPreg.append("8. ¿Cuál es el 2970vo. número primo generado?" + g + "\n");
        txtPreg.append("9. ¿Cuál es el 4169vo. número primo generado?" + h + "\n");
        txtPreg.append("10. ¿Cuál es el 4269vo. número primo generado?" + i + "\n");
        txtPreg.append("11. ¿Cuál es el 5067vo. número primo generado?" + j + "\n");
        txtPreg.append("12. ¿Cuál es el 7615vo. número primo generado?" + k + "\n");
        txtPreg.append("13. ¿Cuál es el 8824vo. número primo generado?" + l + "\n");
        txtPreg.append("14. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 1129?" + m + "\n");
        txtPreg.append("15. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 1889?" + n + "\n");
        txtPreg.append("16. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 5851?" + o + "\n");
        txtPreg.append("17. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 9791?" + p + "\n");
        txtPreg.append("18. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 30467?" + q + "\n");
        txtPreg.append("19. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 43913?" + r + "\n");
        txtPreg.append("20. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 61339?" + s + "\n");
        txtPreg.append("21. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 77513?" + t + "\n");
        txtPreg.append("22. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 88129?" + u + "\n");
        txtPreg.append("23. ¿Cuántos saltos y tiempo tarda el programa para encontrar el 104717?" + v + "\n");
        txtPreg.append("24. ¿Cuál fue el promedio de saltos utilizados para todas las búsquedas (preguntas 13 a 22)?" + w + "\n");
        txtPreg.append("25. ¿Cuál fue el tiempo promedio de búsqueda (preguntas 13 a 22)?" + x + "\n");

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPreg.setColumns(20);
        txtPreg.setRows(5);
        jScrollPane1.setViewportView(txtPreg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPreg;
    // End of variables declaration//GEN-END:variables
}
